<?php

/**
 * BaseTemplates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * 
 * @method string    getLabel() Returns the current record's "label" value
 * @method Templates setLabel() Sets the current record's "label" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemplates extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('templates');
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}