<?php

/**
 * Template
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos E. Caballero B.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Template extends BaseTemplate
{
}
