documents_list:
  url: document.html
  param: { module: document, action: index }

documents_new:
  url: document/new.html
  param: { module: document, action: new }

homepage:
  url:   /
  param: { module: frontpage, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

